spring:
  application:
    name: CONFIG-SERVER-DEFAULT
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8767/eureka/
